export const full_flag_list = [
  {
    country: "Argentina",
    hasStripes: true,
    numberOfColors: 3,
    hasStars: false,
    stripeDirection: "horizontal",
    hasCircles: true, // The sun is a circle
    colours: ["blue", "white", "yellow"],
  },
  {
    country: "Canada",
    hasStripes: true,
    numberOfColors: 2,
    hasStars: false,
    stripeDirection: "vertical",
    hasCircles: false,
    colours: ["red", "white"],
  },
  {
    country: "Belgium",
    hasStripes: true,
    numberOfColors: 3,
    hasStars: false,
    stripeDirection: "vertical",
    hasCircles: false,
    colours: ["black", "yellow", "red"],
  },
  {
    country: "China",
    hasStripes: false,
    numberOfColors: 2,
    hasStars: true,
    stripeDirection: null, // No stripes
    hasCircles: false,
    colours: ["red", "yellow"],
  },
  {
    country: "Australia",
    hasStripes: false,
    numberOfColors: 3,
    hasStars: true,
    stripeDirection: null, // No stripes
    hasCircles: false,
    colours: ["blue", "white", "red"],
  },
  {
    country: "Germany",
    hasStripes: true,
    numberOfColors: 3,
    hasStars: false,
    stripeDirection: "horizontal",
    hasCircles: false,
    colours: ["black", "red", "yellow"],
  },
  {
    country: "United States",
    hasStripes: true,
    numberOfColors: 3,
    hasStars: true,
    stripeDirection: "horizontal",
    hasCircles: false,
    colours: ["red", "white", "blue"],
  },
  {
    country: "United Kingdom",
    hasStripes: false,
    numberOfColors: 3,
    hasStars: false,
    stripeDirection: null, // Cross pattern
    hasCircles: false,
    colours: ["red", "white", "blue"],
  },
  {
    country: "Ukraine",
    hasStripes: true,
    numberOfColors: 2,
    hasStars: false,
    stripeDirection: "horizontal",
    hasCircles: false,
    colours: ["blue", "yellow"],
  },
  {
    country: "Venezuela",
    hasStripes: true,
    numberOfColors: 3,
    hasStars: true,
    stripeDirection: "horizontal",
    hasCircles: false,
    colours: ["yellow", "blue", "red"],
  },
  {
    country: "Netherlands",
    hasStripes: true,
    numberOfColors: 3,
    hasStars: false,
    stripeDirection: "horizontal",
    hasCircles: false,
    colours: ["red", "white", "blue"],
  },
  {
    country: "European Union",
    hasStripes: false,
    numberOfColors: 2,
    hasStars: true,
    stripeDirection: null, // No stripes
    hasCircles: false,
    colours: ["blue", "yellow"],
  },
  {
    country: "Japan",
    hasStripes: false,
    numberOfColors: 2,
    hasStars: false,
    stripeDirection: null, // No stripes
    hasCircles: true, // Red circle
    colours: ["white", "red"],
  },
  {
    country: "Switzerland",
    hasStripes: false,
    numberOfColors: 2,
    hasStars: false,
    stripeDirection: null, // No stripes
    hasCircles: false,
    colours: ["red", "white"],
  },
  {
    country: "Romania",
    hasStripes: true,
    numberOfColors: 3,
    hasStars: false,
    stripeDirection: "vertical",
    hasCircles: false,
    colours: ["blue", "yellow", "red"],
  },
];
